### ISSUE TITLE
calculate_haplotype_statistics.py not working

### ISSUE THREAD

**Issue by vibansal** [vibansal/HapCUT2#26]
python3 calculate_haplotype_statistics.py 
Traceback (most recent call last):
  File "calculate_haplotype_statistics.py", line 763, in <module>
    args = parse_args()
  File "calculate_haplotype_statistics.py", line 29, in parse_args
    parser.add_argument('-i', '--indels', nargs='?', action="store_true", help='Use this flag to consider indel variants. Default: Indels ignored.',default=False)
  File "/home/vbansal/opt/python-3.6.2/lib/python3.6/argparse.py", line 1334, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'nargs'

**Comment by vibansal** [comment]
fixed in recent update
